// Placeholder. Real types are generated by `npm run db:types` after the
// Supabase project is linked. For now we declare a minimal Database shape
// so the supabase client is typed.
//
// To generate real types:
//   1. supabase login
//   2. supabase link --project-ref <ref>
//   3. npm run db:types
//
// That command overwrites this file.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
